{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
    chart: {{ include "bantu-crm.chart" . }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  local:
    path: {{ .Values.global.dataPath }}/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ include "bantu-crm.nodeName" . }}
{{- end }}

