{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mysql
    chart: {{ include "bantu-crm.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.database | quote }}
  MYSQL_USER: {{ .Values.mysql.secrets.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.password | quote }}
{{- end }}

