apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "bantu_root_password_2024"
  MYSQL_DATABASE: "bantu_crm"
  MYSQL_USER: "bantu_user"
  MYSQL_PASSWORD: "bantu_user_password_2024"

