apiVersion: v2
name: bantu-crm
description: BANTU CRM 系统一体化 Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - crm
  - mysql
  - redis
  - minio
  - mongodb
  - chroma
  - metabase
  - activiti
home: https://github.com/bantu/crm-configuration
sources:
  - https://github.com/bantu/crm-configuration
maintainers:
  - name: BANTU Team
    email: dev@bantu.com

